enum Permission {
  TAGS_VIEW = 'tags.view',
  TAGS_CREATE = 'tags.create',
  TAGS_UPDATE = 'tags.update',
  TAGS_DELETE = 'tags.delete',
  NOTES_VIEW = 'notes.view',
  NOTES_CREATE = 'notes.create',
  NOTES_UPDATE = 'notes.update',
  NOTES_DELETE = 'notes.delete',
  MANAGEMENT_MATERIALS = 'management.materials',
  MESSAGES_VIEW = 'messages.view',
  MESSAGES_MANAGE = 'messages.manage',
  DOCUMENTS_CREATE = 'documents.create',
  DOCUMENTS_VIEW = 'documents.view',
  DOCUMENTS_DOWNLOAD = 'documents.download',
  DOCUMENTS_DELETE = 'documents.delete',
  COUNTRIES_VIEW = 'countries.view',
  STATES_VIEW = 'states.view',
  SUBURBS_VIEW = 'suburbs.view',
  SUBURBS_CREATE = 'suburbs.create',
  SUBURBS_UPDATE = 'suburbs.update',
  SUBURBS_DELETE = 'suburbs.delete',
  ADDRESSES_VIEW = 'addresses.view',
  ADDRESSES_UPDATE = 'addresses.update',
  CONTACTS_VIEW = 'contacts.view',
  CONTACTS_UPDATE = 'contacts.update',
  CONTACTS_CREATE = 'contacts.create',
  CONTACTS_DELETE = 'contacts.delete',
  CREDIT_NOTES_MANAGE = 'finance.credit_notes.manage',
  CREDIT_NOTES_MANAGE_LOCKED = 'finance.credit_notes.manage_locked',
  CREDIT_NOTES_VIEW = 'finance.credit_notes.view',
  MEETINGS_CREATE = 'meetings.create',
  MEETINGS_VIEW = 'meetings.view',
  MEETINGS_DELETE = 'meetings.delete',
  LOCATIONS_VIEW = 'locations.view',
  LOCATIONS_CREATE = 'locations.create',
  LOCATIONS_UPDATE = 'locations.update',
  LOCATIONS_MODIFY_MEMBERS = 'locations.modify_members',
  LOCATIONS_MODIFY_SUBURB = 'locations.modify_suburbs',
  JOBS_TASK_MANAGE = 'jobs.tasks.manage',
  JOBS_VIEW = 'jobs.view',
  JOBS_ASSIGN_STAFF = 'jobs.assign_staff',
  JOBS_MANAGE_INBOX = 'jobs.manage_inbox',
  JOBS_MANAGE_TAGS = 'jobs.manage_tags',
  JOBS_UPDATE = 'jobs.update',
  JOBS_DELETE = 'jobs.delete',
  JOBS_CREATE = 'jobs.create',
  JOBS_MANAGE_CONTACTS = 'jobs.manage_contacts',
  JOBS_MANAGE_NOTES = 'jobs.manage_notes',
  JOBS_MANAGE_MESSAGES = 'jobs.manage_messages',
  JOBS_MANAGE_JOBS = 'jobs.manage_jobs',
  JOBS_MANAGE_RECURRING = 'jobs.manage_recurring',
  JOBS_USAGE_VIEW = 'jobs.usage.view',
  JOBS_USAGE_MATERIALS_MANAGE = 'jobs.usage.materials.manage',
  JOBS_USAGE_MATERIALS_UPDATE = 'jobs.usage.materials.update',
  JOBS_USAGE_MATERIALS_CREATE = 'jobs.usage.materials.create',
  JOBS_USAGE_MATERIALS_DELETE = 'jobs.usage.materials.delete',
  JOBS_AREAS_MANAGE = 'jobs.areas.manage',
  INVOICES_VIEW = 'finance.invoices.view',
  INVOICES_MANAGE = 'finance.invoices.manage',
  INVOICES_MANAGE_LOCKED = 'finance.invoices.manage_locked',
  OPERATIONS_RUNS_VIEW = 'operations.runs.view',
  OPERATIONS_RUNS_MANAGE = 'operations.runs.manage',
  OPERATIONS_TASKS_VIEW = 'operations.tasks.view',
  OPERATIONS_STAFF_VIEW = 'operations.staff.view',
  OPERATIONS_VEHICLES_VIEW = 'operations.vehicles.view',
  PURCHASE_ORDERS_VIEW = 'finance.purchase_orders.view',
  PURCHASE_ORDERS_MANAGE = 'finance.purchase_orders.manage',
  PURCHASE_ORDERS_MANAGE_LOCKED = 'finance.purchase_orders.manage_locked',
  PAYMENTS_CREATE = 'finance.payments.create',
  PAYMENTS_FORWARD = 'finance.payments.forward',
  PAYMENTS_VIEW = 'finance.payments.view',
  PAYMENTS_RECEIVE = 'finance.payments.receive',
  JOBS_USAGE_EQUIPMENT_MANAGE = 'jobs.usage.equipment.manage',
  JOBS_USAGE_EQUIPMENT_UPDATE = 'jobs.usage.equipment.update',
  JOBS_USAGE_EQUIPMENT_CREATE = 'jobs.usage.equipment.create',
  JOBS_USAGE_EQUIPMENT_DELETE = 'jobs.usage.equipment.delete',
  ASSESSMENT_REPORTS_VIEW = 'assessment_reports.view',
  ASSESSMENT_REPORTS_MANAGE = 'assessment_reports.manage',
  ASSESSMENT_REPORTS_APPROVE = 'assessment_reports.approve',
  ASSESSMENT_REPORTS_MANAGE_CANCELLED = 'assessment_reports.manage_cancelled',
  JOBS_USAGE_LABOUR_CREATE = 'jobs.usage.labour.create',
  JOBS_USAGE_LABOUR_UPDATE = 'jobs.usage.labour.update',
  JOBS_USAGE_LABOUR_DELETE = 'jobs.usage.labour.delete',
  JOBS_USAGE_LABOUR_MANAGE = 'jobs.usage.labour.manage',
  ALLOWANCES_TYPES_VIEW = 'allowances.view',
  ALLOWANCES_TYPES_MANAGE = 'management.jobs.allowances',
  JOBS_USAGE_ALLOWANCES_MANAGE = 'jobs.usage.allowances.manage',
  JOBS_USAGE_ALLOWANCES_APPROVE = 'jobs.usage.allowances.approve',
  FINANCIALS_REPORTS_VIEW = 'finance.financial.reports.view',
  USERS_VIEW = 'users.view',
  USERS_CREATE = 'users.create',
  USERS_UPDATE = 'users.update',
  USERS_DELETE = 'users.delete',
  ROLES_VIEW = 'roles.view',
  ROLES_UPDATE = 'roles.update',
  ROLES_DELETE = 'roles.delete',
  ROLES_CREATE = 'roles.create',
  TEAMS_VIEW = 'teams.view',
  TEAMS_UPDATE = 'teams.update',
  TEAMS_DELETE = 'teams.delete',
  TEAMS_CREATE = 'teams.create',
  TEAMS_MODIFY_MEMBERS = 'teams.modify_members',
  JOBS_USAGE_REIMBURSEMENTS_MANAGE = 'jobs.usage.reimbursements.manage',
  JOBS_USAGE_REIMBURSEMENTS_APPROVE = 'jobs.usage.reimbursements.approve',
  LAHA_COMPENSATIONS_VIEW = 'laha.view',
  LAHA_COMPENSATIONS_MANAGE = 'management.jobs.laha',
  JOBS_USAGE_LAHA_MANAGE = 'jobs.usage.laha.manage',
  JOBS_USAGE_LAHA_APPROVE = 'jobs.usage.laha.approve'
}

export const UsersPermission = [
  Permission.USERS_CREATE,
  Permission.USERS_DELETE,
  Permission.USERS_UPDATE,
  Permission.USERS_VIEW
];

export const LocationsPermissions = [
  Permission.LOCATIONS_VIEW,
  Permission.LOCATIONS_CREATE,
  Permission.LOCATIONS_UPDATE,
  Permission.LOCATIONS_MODIFY_MEMBERS,
  Permission.LOCATIONS_MODIFY_SUBURB
];

export const TagsPermission = [
  Permission.TAGS_CREATE,
  Permission.TAGS_DELETE,
  Permission.TAGS_VIEW,
  Permission.TAGS_UPDATE
];

export const ContractsPermission = [
  Permission.CONTACTS_CREATE,
  Permission.CONTACTS_DELETE,
  Permission.CONTACTS_UPDATE,
  Permission.CONTACTS_VIEW
];

export const PermissionsGroupManage = [...UsersPermission, ...LocationsPermissions, ...TagsPermission];

export default Permission;
