apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "frontend.fullname" . }}-ingress
  annotations:
    {{- if .Values.ingress.annotations }}
      {{- toYaml .Values.ingress.annotations | trim | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: {{ include "frontend.fullname" . }}
              servicePort: {{ .Values.service.port }}
